version: "4.34.2"

volumes:                              #перечисляет, какие тома будут исп. для наших контейнеров
    pg_demo:
services:                             #перечисляются докер контейнеры, которые мы будем исп.
  db:                                 #имя контейнера
    image: postgres:latest            #какой образ будет скачан для данного докер контейнера(разворачивается образ postgresDB)
    restart: always                   #автоматический рестарт в любой непонятной ситуации
    #container_name: db
    environment:
      - POSTGRES_DB=pgDB               #имя БД
      - POSTGRES_USER=root             #имя пользователя БД
      - POSTGRES_PASSWORD=root         #пароль пользователя БД
    volumes:                          #какие тома используются этим контейнером
      - pg_demo:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'                   #слевой стороный порт нашего ПК
                                                #справой стороны порт докер контейнера
                                                #127.0 0.1 - позволяет устанавливать соединение и передавать информацию для программ-серверов,
                                                  #работающих на том же компьютере, что и программа-клиент
  app:
    restart: always
    build: .           #путь до файла билда(докер файла), точка - говорит о том, что
                       #файл сборки лежит в той же дирректории, что и docker-compose.yml
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/pgDB'  #при запуске в этой строке имя бд в контейнере будет замененно на IP этого докер контейнера
          #в этом синтаксисе мы передаём переменные среды. URL записанный в SPRING_DATASOURCE_URL переопределяет URL из .properties
      JAVA_OPTS: '-Xmx512m'